## エラーで立ち止まらないようにする

```ruby
puts 1
begin ####
    number = 0
    answer = 100 / number
    puts answer
rescue ZeroDivisionError => e ###
    p e
ensure ###
    puts 2
end
```
```ruby
エラー内容の表示
puts 1
begin
    number = 0
    answer = 100 / number
    puts answer
rescue ZeroDivisionError => e
    puts "0では割り算できません"
    # puts e.message
    # p e.backtrace
    STDERR.puts e.backtrace #STDERRはエラー出力に表示される
ensure
    puts 2
end
```
## ensure
```ruby
def test_exception(number)
    puts 2
    begin
        puts 3
        answer = 100 / number
        return answer
        puts 4
    rescue ZeroDivisionError => e　　##ここのエラーは下のrescueに送られる
        puts 5
        raise e
    ensure         ## 必ず実行される
        puts 6
    end
end

puts 1

begin
    answer = test_exception(0)
    puts 7
rescue ZeroDivisionError => e　　　　##上のエラーが送られてくる
    puts 8
    p e
end
```
